### PR TITLE
sync init

### PR DESCRIPTION
**Pull request by WindzCUHK**
requirement:
1. sync init
2. return error, if any child daemon failed

TODO:
- [ ] remove the 1st update() in start()

### CODE REVIEW

**Comment by WindzCUHK** [comment]
related: https://github.com/yahoojapan/athenz-authorizer/pull/46

**Comment by kevindiu** [comment]
We need to block fetching(processing) policy before key is fetched because processing policy requires pubkey or jwk is ready.

**Comment by WindzCUHK** [comment]
> We need to block fetching(processing) policy before key is fetched because processing policy requires pubkey or jwk is ready.

fixed.

---

remove the 1st update() in start() in PR? or this https://github.com/yahoojapan/athenz-authorizer/pull/46?

**Comment by kevindiu** [comment]
jwkd also needs to be updated before the policy is updated.
I am thinking which way is better, adding a success channel to start() or add init() function...

**Comment by WindzCUHK** [comment]
policyd does not depends on jwkd.
roleProcessor needs to wait for jwkd or pubkeyd, so the sidecar just wait for `Authorizerd.Init()` should be OK.

**Comment by WindzCUHK** [comment]
init event usually fails by mis-config (better to crash)
on-going event (update fail) usually due to temporary down of dependent services (better NOT crash)

It is better to separate init event (1st success/fail) and on-going event, or separate the method.

**Comment by kevindiu** [comment]
yes, both ways are fine but init() seems better. :)

LGTM

**Pull request merged**
