### PR TITLE
[major] rename options

### LINKED ISSUE #37: fix inconsistent configuration naming
1. `WithPolicyExpiredDuration` is missing in `authorizerd.go`
1. https://github.com/yahoojapan/athenz-authorizer/blob/master/option.go
    1. `WithPolicyExpireMargin` => `WithPolicyExpireMarginDur`
    1. `WithPolicyExpiredDuration` => `WithPolicyFlushDur`
    1. `WithPolicyEtagFlushDur` => `WithPolicyEtagFlushDur`
    1. `WithPolicyErrRetryInterval` => `WithPolicyErrRetryDur`
    1. `WithPolicyRefreshDuration` => `WithPolicyRefreshDur`

### PR DESCRIPTION
**Pull request by WindzCUHK**
# Description

Fix naming consistency.
Depends on: #50, #65

### changes
- `WithTransport` => `WithHTTPClient`
- fix inconsistent naming (related: #37)
- export `WithPolicyPurgePeriod` option, change its default to `1h`
    - ExpiryMargin == 3 hours
    - expiry time should be > 3h
    - purge time <= expiry time / 2
    - 3 hours / 2 = 1.5 hours, use **1 hour** to be exact

## Type of change

- [ ] Bug fix
- [ ] New feature
- [x] Refactoring (no functional changes, no api changes)
- [ ] Non-code changes (update documentation, pipeline, etc.)

### Flags

- [x] breaks backward compatibility
- [x] requires a documentation update
- [ ] has untestable code

## Related issue/PR

- Closes #37, https://github.com/yahoojapan/authorization-proxy/issues/37

---

## Checklist

- [x] Followed the guidelines in the CONTRIBUTING document
- [x] Added prefix `[major]`/`[minor]`/`[patch]`/`[skip]` in the PR title
- [x] Tested and linted the code
- [x] Commented the code
- [x] Made corresponding changes to the documentation
- [x] Confirmed no dropping in test coverage (by [Codecov](https://codecov.io/gh/yahoojapan/athenz-authorizer/pulls))
- [x] Passed all pipeline checking
- [x] Approved by >1 reviewer

## Checklist for maintainer
- [ ] Use `Squash and merge`
- [ ] Double-confirm the merge message has prefix `[major]`/`[minor]`/`[patch]`/`[skip]`
- [ ] Delete the branch after merge

### CODE REVIEW

**Comment by ssunorz** [comment]
I thought it was inconsistent, but may not be enough to fix.

https://github.com/yahoojapan/athenz-authorizer/blob/5ff7f922dc49dbdd41f2006facf44a4dc97a1dbb/pubkey/daemon.go#L66
https://github.com/yahoojapan/athenz-authorizer/blob/5ff7f922dc49dbdd41f2006facf44a4dc97a1dbb/policy/fetcher.go#L64

**Comment by WindzCUHK** [comment]
> I thought it was inconsistent, but may not be enough to fix.
@ssunorz fixed, 446d005

**Comment by ssunorz** [comment]
Unused constant
https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/role/processor.go#L29

In addition, is it better to use camelcase?
https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/access/processor.go#L30

**Comment by ssunorz** [comment]
`time.Duration()` is redundant.
https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/policy/daemon.go#L344

**Comment by WindzCUHK** [comment]
> Unused constant
> https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/role/processor.go#L29
> 
> In addition, is it better to use camelcase?
> https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/access/processor.go#L30

> `time.Duration()` is redundant.
> https://github.com/yahoojapan/athenz-authorizer/blob/442bf56828df0724a00b649994e1546a3b911a69/policy/daemon.go#L344

fixed in: a67b9ba

**Pull request merged**
