### PR TITLE
fix etag exists, cache not update

### PR DESCRIPTION
**Pull request by kevindiu**

### CODE REVIEW

**Comment by kpango** [comment]
LGTM but you can remove upd variable from daemon.go and you should remove return variable of upd

**Comment by kevindiu** [comment]
Can I keep the upd variable here?

**Comment by WindzCUHK** [comment]
https://github.com/yahoojapan/athenz-authorizer/blob/b56348ee1371d14e26ce2af5e4cc5226f548ea7d/policy/daemon.go#L323-L328

I think we also have problem about Etag here.
When `etagExpTime` is configured wrongly,
there will be a case that Etag is not expired, but policy expired.
As Athenz server return 304, policy will keep empty.

Should we just set the Etag expiry time according to the policy expiry time.
```go
p.etagCache.SetWithExpire(domain, &etagCache{eTag, sp}, sp.SignedPolicyData.Expires.UnixNano().Sub(p.expireMargin)) 
```

**Comment by kevindiu** [comment]
I think your suggestion also cause problem that the expire margin is small than the policy refresh duration and the policy cache will be deleted before it is expired...
Anyway both cases will be handled by the expire hook

**Comment by WindzCUHK** [comment]
expire hook cannot help on this
policy expire > expire hook > fetch with Etag > 304 > ❗️**set rp cache with expired policy in etag cache again**

**Comment by kevindiu** [comment]
But I think user need to understand these parameter or they can just use the default value.

**Comment by WindzCUHK** [comment]
@kevindiu 
I mean that it is not necessary to have use `etagExpTime` for policy,
just use the policy expiry time to expire the Etag cache is simpler.

What cache do you refer to?
I mean the etag cache returned below.
https://github.com/yahoojapan/athenz-authorizer/blob/b56348ee1371d14e26ce2af5e4cc5226f548ea7d/policy/daemon.go#L291-L296

**Comment by kevindiu** [comment]
Maybe we should create an issue and discuss it on the issue.

**Comment by WindzCUHK** [comment]
created: https://github.com/yahoojapan/athenz-authorizer/issues/29

**Comment by WindzCUHK** [comment]
https://github.com/yahoojapan/athenz-authorizer/issues/29

**Comment by WindzCUHK** [comment]
LGTM

**Comment by kpango** [comment]
LGTM

**Pull request merged**
